### ISSUE TITLE
Wrap timezone abbreviations containing numbers or '+' or '-' with angle brackets.

### ISSUE THREAD

**Issue by mcpat** [alexandrebelloni/tzdump#1]
Some timezone abbreviations in the database (for example Europe/Minsk) contain numeric characters or the '+' or '-' signs. Those have to be wrapped by angle brackets ('<' and '>') to be correctly interpreted.
I attached a patch to fix the behaviour. The functionality of the generated files has been validated with uclibc.

[0001-CHANGE-wrap-timezone-abbreviations-with-angle-bracke.patch.txt](https://github.com/alexandrebelloni/tzdump/files/915807/0001-CHANGE-wrap-timezone-abbreviations-with-angle-bracke.patch.txt)

**Comment by alexandrebelloni** [comment]
Seems to be the right thing to do. However, can you create a proper pull request so I can comment on the patch itself?

I would prefer to avoid the use of goto.

**Comment by mcpat** [comment]
Yep, did it.
